 CREATE TABLE nba_table3 (
 	indices INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
 	Player	VARCHAR(200) NOT NULL,
 	Pos	    VARCHAR(5) NOT NULL,
 	Age		INT NOT NULL,
 	Tm		VARCHAR(3),
 	G		INT,
 	GS		INT,
	MP DOUBLE,	 FG DOUBLE,	 FGA DOUBLE,	 FG_per DOUBLE,
	3P DOUBLE,	 3PA DOUBLE, 3P_per DOUBLE,
	2P DOUBLE,	 2PA DOUBLE, 2P_per DOUBLE,	 eFG_per	DOUBLE,
	FT DOUBLE,	 FTA DOUBLE, FT_per DOUBLE,
	ORB DOUBLE,	 DRB DOUBLE, TRB DOUBLE,	
	AST DOUBLE,	 STL DOUBLE, BLK DOUBLE,	 TOV DOUBLE,	
	PF DOUBLE,	 PTS DOUBLE, Year INT
    ); 